### ISSUE TITLE
Cert generation instructions incomplete

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/hegel#10]
Expected the following from the README to work without extra inputs etc

```
mkdir ./certs
openssl genrsa -des3 -passout pass:x -out ./certs/server.pass.key 2048
openssl rsa -passin pass:x -in ./certs/server.pass.key -out ./certs/server.key
openssl req -new -key ./certs/server.key -out ./certs/server.csr
openssl x509 -req -sha256 -days 365 -in ./certs/server.csr -signkey ./certs/server.key -out ./certs/server.crt
export HEGEL_TLS_CERT=./certs/server.crt
export HEGEL_TLS_KEY=./certs/server.key
```

Actual result:

<img width="1562" alt="Screenshot 2020-04-09 at 10 16 09" src="https://user-images.githubusercontent.com/6358735/78878985-2def1300-7a4b-11ea-9035-3718924542a5.png">

Suggested solution:

Either inform the user what to enter for each input, or give them a sample like ACME CO and pre-populate the flags.

**Comment by chrisdoherty4** [comment]
Thanks for reporting. We'll continue to address documentation but given this issue hasn't seen any movement in quite some time, we'll close for now.
