### ISSUE TITLE
Implement cloud-init integration

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/hegel#119]
Write a cloud-init [data source](https://cloudinit.readthedocs.io/en/latest/topics/datasources.html) adapter for the Hegel Metadata API.

**Comment by displague** [comment]
Related conversation in https://github.com/tinkerbell/hegel/issues/44

One limitation that we can expect with a Hegel data source adapter is that cloud-init will not be able to detect the cloud environment as a Hegel environment based on machine properties (typically DMI in the case of virtual machine cloud providers).  It is likely that a `ds=hegel` kernel parameter (or similar) will be needed by clients.
