### ISSUE TITLE
E2E service tests

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/hegel#146]
To ensure Hegel does in-fact function it would be useful to have some sort of e2e test that merely launches the Hegel image and hits a few endpoints. 

This could be by using a mock back-end or a light weight Kubernetes cluster implementation - something that can run on the CI in a reasonable time frame.

At a minimum, ensuring we can launch the service would be useful.

**Comment by jacobweinstock** [comment]
Is there a way to test that the ec2 metadata endpoints are compliant to the standard in any way? that might be a nice addition too.

**Comment by chrisdoherty4** [comment]
Compliance tests are a good thought although I'm not sure how different they'd be vs normal e2e tests. I mention that because we don't support all AWS EC2 endpoints, for example, and never will as they aren't all relevant. 

Do you have a particular train of thought on a differentiating factor between typical E2E tests and compliance tests in this case?

**Comment by chrisdoherty4** [comment]
Addressed in #157 and #158
