### ISSUE TITLE
Metadata path prefix should be configurable

### ISSUE THREAD

**Issue by displague** [tinkerbell/hegel#32]
References such as `_packet/`, should be configurable at runtime, as in:
https://github.com/tinkerbell/hegel/blob/4e05329f4eb5bae4dde1ce7604515807f44c50f1/http_server.go#L14

The default should be `_tinkerbell`.

The command line, environment variables, or a configuration file would be a suitable way to pass this information.  `viper` is one library that could accommodate all three methods.

**Comment by chrisdoherty4** [comment]
How about switching to z pages instead as default? They could still be configurable but z pages seems to be the norm these days.

```
/healthz
/versionz
```

**Comment by chrisdoherty4** [comment]
The `/_packet` endpoints have been deprecated in favor of the z pages approach common in micro services.
