### ISSUE TITLE
HTTP Handlers for EC2 metadata seem incorrect

### ISSUE THREAD

**Issue by micahhausler** [tinkerbell/hegel#61]
## Expected Behaviour

I don't have a full list of the broken paths, but a number of the queries in [http-server/http_handlers.go: ec2Filters](https://github.com/tinkerbell/hegel/blob/9f5da0/http-server/http_handlers.go#L26-L48) are invalid. 

For example: `{ "/meta-data/plan":   ".metadata.instance.plan" }` where [`github.com/tinkerbell/tink/protos/packet/packet.proto`](https://github.com/tinkerbell/tink/blob/a56e5cf9/protos/packet/packet.proto) doesn't have a corresponding field.

## Steps to Reproduce (for bugs)
1. Boot and SSH into a tink worker
2. `curl -s $HEGEL_URL:50061/2009-04-04/meta-data/plan` 

## Context
Its hard to know other than trial and error what metadata fields are supported and will work if I want to use something like CloudInit

**Comment by displague** [comment]
I've found that `cloud-init query -a` is missing some keys. When running `cloud-init query -f '{{ ds.meta_data.operating_system.version }}'`, I think we can see evidence of a problem.
```
WARNING: Could not render jinja template variables in file 'query commandline': 'version'
CI_MISSING_JINJA_VAR/version
```

As `curl -D- https://.../2009-04-04/meta-data/` and `cloud-init query -l ds.meta_data` show, the dictionary and array paths do not end with `/`, as they do in other cloud environments.  This character seems to hint to cloud-init that directory traversal is possible.  I'm not entirely convinced that this is the only hint that is needed, or that this is the authoritative hint. I haven't been able to identify spec documentation or pinpoint the cloud-init code that defines this behavior.

**Comment by chrisdoherty4** [comment]
@displague 

> would this represent a Tinkerbell workflow?

Probably not. An AMI is quite Amazon specific. Trying to give it semantics beyond what Amazon defines could be misleading.

**Comment by chrisdoherty4** [comment]
I did an investigation to understand the existing implementation and compare it with Amazon EC2 and Equinix Metal metadata. TL;DR, (1) we aren't serving EC2 instance metadata; (2) we don't seem to be serving Equnix Metal metadata _properly_.

#### EC2 IMD 2009-04-04

```
{
    "ami-id": "string",
    "ami-launch-index": "string",
    "ami-manifest-path": "string",
    "ancestor-ami-ids": [],
    "block-device-mapping": {
        "ami": "string",
        "ebs<N>": "<N> is a number represent EBS device so there can be many `ebs` entries",
        "ephemeral<N>": "<N> is an index for non-NVMe instance store volumes."
        "root": "string",
        "swap": "string",
    },
    "hostname": "string",
    "instance-action": "string",
    "instance-type": "string",
    "kernel-id": "string",
    "local-hostname": "string",
    "local-ipv4": "string",
    "mac": "string",
    "network.interfaces.macs.{mac}": {
        "local-hostname": "string",
    },
    "placement.availability-zone": "string",
    "product-codes": "string",
    "public-hostname": "string",
    "public-ipv4": "string",
    "public-keys": [
        {
            "openssh-key": "string",
        }
    ],
    "ramdisk-id": "string",
    "reservation-id": "string",
    "security-groups": [],
}
```

#### Equinix instance metadata

```
# /metadata yields the full JSON object.
{
    "id": "2885032e-61a8-4786-bd26-7b2e2e6ba1ea",
    "hostname": "metadata",
    "iqn": "iqn.2017-11.net.equinix:device.2885032e",
    "operating_system": {
        "slug": "ubuntu_20_04",
        "distro": "ubuntu",
        "version": "20.04",
        "license_activation": {
            "state": "unlicensed"
        }
    },
    "plan": "c3.small.x86",
    "class": "c3.small.x86",
    "facility": "ewr1",
    "tags": [],
    "ssh_keys": [
        "ssh-rsa AAAAB3Nza............."
    ],
    "storage": {
        "disks": []
        "raid": []
        "filesystems": []
    },
    "network": {
        "bonding": {
            "mode": 4
        },
        "interfaces": [{
            "name": "p1p1",
            "mac": "0c:c4:7a:e1:3d:d0",
            "bond": "bond0"
        }],
        "addresses": [{
            "id": "63f24352-0997-4f65-babd-6f8c9d048568",
            "address_family": 4,
            "netmask": "255.255.255.254",
            "created_at": "2017-11-04T17:03:20Z",
            "public": true,
            "cidr": 31,
            "management": true,
            "enabled": true,
            "network": "147.75.104.32",
            "address": "147.75.104.33",
            "gateway": "147.75.104.32",
            "parent_block": {
                "network": "147.75.104.32",
                "netmask": "255.255.255.254",
                "cidr": 31,
                "href": "/ips/6c2d45a7-df8b-451e-9d6d-2a1b5476a9d0"
            }
        }],
        "spot": {},
        "volumes": [],
        "api_url": "https://metadata.platformequinix.com/metal",
        "phone_home_url": "http://tinkerbell.ewr1.console.equinix.com/metal/phone-home",
        "user_state_url": "http://tinkerbell.ewr1.console.equinix.com/metal/events"
    }
}
```

Then there's the various endpoints defined at the top `/meta-data` level that seem like EC2 metadata endpoints but aren't really. 

```
curl https://metadata.platformequinix.com/2009-04-04/meta-data
>
instance-id
hostname
iqn
plan
facility
tags
operating-system
public-keys
public-ipv4
public-ipv6
local-ipv4
```

Note the `/metadata` endpoint that serves the full JSON object doesn't actually feature in Hegel out of the box so we don't seem to be providing an Equinix implementation. 

---

The jq filtering occurring internally to Hegel's `/meta-data` endpoint to introspect metadata is focused on the Equnix Metal metadata and the API it results in is Equinix Metal, not EC2 as it claims.

I think this needs redesigning. Assuming we want to support multiple APIs, Amazon EC2 and Equinix for example, it would be nice to configure which one you want on launch (I've talked about this in a [separate issue](https://github.com/tinkerbell/hegel/issues/99) and configure the data source. The 'data model' does provide the data source configuration albeit in a somewhat convoluted way today.

**Comment by displague** [comment]
> Clearly, the paths and filters correlate to Equinix metal, not EC2, and we don't expose a /metadata endpoint like the [Equinix docs](https://metal.equinix.com/developers/docs/server-metadata/metadata/) suggest should exist. I'm not sure what the purpose of the 2009-04-04 is in the Equinix metadata standard but it might be a source of confusion given it's the same date as one of the EC2 versions.

The 2009-04-04 compatibility, specifically the fields you called out, offers a path well supported by historical and current versions of cloud-init and similar tools. The pattern is utilized in Equinix Metal OS provisioning. I'd leave it to @nshalman to say whether or not this is facilitated by Hegel. I believe a predecessor is in use and the intention was to adopt Hegel in the future (with backward compatibility for the current service). This may have changed.

Go templating offers a way to offer bespoke metadata URL mapping and I wonder if this should be a matter of user configuration (with standardized default templates).

**Comment by chrisdoherty4** [comment]
We discussed this during a community meeting and have opted to replace existing APIs with a [Hegel metadata API](https://github.com/tinkerbell/proposals/tree/main/proposals/0027) that will be integrated with cloud-init.
