### ISSUE TITLE
remove or fix hegelc

### ISSUE THREAD

**Issue by displague** [tinkerbell/hegel#67]
## Expected Behaviour

It is not clear what functionality hegelc adds to this project. 

## Current Behaviour
If this is a useful component, the default hostname should not be metadata.packet.net.

## Possible Solution

Remove hegelc or improve the README.md to explain the purpose and change the hostname to be configurable (environment variable, command line) with a default like 'hegel' or 'metadata' that will work well in docker-compose, mdns, or DNS domain search environments.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by splaspood** [comment]
Excellent call out re metadata.packet.net.   I think a hegel 'client' is useful for development and we should probably enhance hegelc to support all the various grpc functions available in the hegel 'API'.

**Comment by displague** [comment]
Created https://github.com/tinkerbell/hegel/pull/76 to address this
