### ISSUE TITLE
hegel thinks a request for metadata comes from the gateway IP

### ISSUE THREAD

**Issue by johalun** [tinkerbell/hegel#79]
I have a vagrant setup with a provisioner and a target host. Both in VMs. When the target host (10.214.134.12) requests metadata, hegel (10.214.134.11) sees the userIP for the request being 10.214.134.1 which is the gateway so it denies the request.

## Expected Behaviour
I expect my action doing `curl http://10.214.134.11:50061/metadata` to receive the hardware json file for the host.

## Current Behaviour
Hegel denies the request because it thinks the request is coming from the gateway IP.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
1. Setup vagrant to create two VMs, a provisioner and a target host to provision.
2. Create a docker image with an action to curl the provisioner for metadata
3. Run workflow with that action

## Context
I want to access metadata like hostname and network config in my action during provisioning.

## Your Environment
Ubuntu 20.04
Vagrant with VirtualBox backend

**Comment by johalun** [comment]
hegel log output
```
hegel_1                     | {"level":"info","ts":1643240394.791924,"caller":"http-server/http_handlers.go:109","msg":"got ip from request","service":"github.com/tinkerbell/hegel","pkg":"main","userIP":"10.214.134.1"}
hegel_1                     | {"level":"info","ts":1643240394.7938175,"caller":"http-server/http_handlers.go:113","msg":"failed to get hardware by ip","service":"github.com/tinkerbell/hegel","pkg":"main","userIP":"10.214.134.1","error":"rpc error: code = Unknown desc = SELECT: sql: no rows in result set"}
```

**Comment by mmlb** [comment]
How are you running hegel? Behind some sort of proxy? If so you need to set the XFF var to something appropriate `TRUSTED_PROXIES=$proxy-ip` or `TRUSTED_PROXIES=$somesubnet/cidr`.

**Comment by johalun** [comment]
It's running on the tink server using the included docker-compose to start all services. There's no proxy, just a simple virtual network with two hosts. If this is just the nature of virtual networks, possibly due to NAT, maybe letting hegel first check for an X-Forwarded-For header before relying on remote address could be a solution (could be good to do this either way)? Something like (copied from SO - I'm no Go programmer...)
```
func ReadUserIP(r *http.Request) string {
    IPAddress := r.Header.Get("X-Real-Ip")
    if IPAddress == "" {
        IPAddress = r.Header.Get("X-Forwarded-For")
    }
    if IPAddress == "" {
        IPAddress = r.RemoteAddr
    }
    return IPAddress
}
```

**Comment by mmlb** [comment]
hegel already does this, but doesn't trust xff unless the client's ip is trusted (directly of by being in a subnet). Which docker-compose are you using? the one in tinkerbell/tink repo or tinkerbell/sandbox?

**Comment by mmlb** [comment]
Yep I just noticed none of the docker-compose files use a proxy either, so its likely due to your network, NAT doesn't add any of the xff headers though right? Doesn't sound like its going to work until you can get hegel and your machine to talk directly or via a http proxy I think.

**Comment by johalun** [comment]
Not according to what I can see

https://github.com/tinkerbell/hegel/blob/e570bc4f618898e799ee78ee1f5078ed9ab4d0d4/http-server/http_handlers.go#L260-L266

**Comment by mmlb** [comment]
> Not according to what I can see

Do you mean not parsing `xff` headers? It does so via a middleware: https://github.com/tinkerbell/hegel/blob/e570bc4f618898e799ee78ee1f5078ed9ab4d0d4/http-server/http_server.go#L62-L63
xff.HTTPHandler updates req.RemoteAddr if trusts the proxy/proxies ([here](https://github.com/packethost/xff/blob/master/xff.go#L130-L135))

**Comment by mmlb** [comment]
@johalun any more updates? If not, I think we should close this issue.

**Comment by johalun** [comment]
So, I tried setting the XFF header in my curl request and it still fails. Provisioner and target host are both on the same subnet as you can see in the initial post. But according to what you say my environment should satisfy the requirements...

**Comment by mmlb** [comment]
Did you also set the `TRUSTED_PROXIES` env var for hegel?

**Comment by johalun** [comment]
I will try that

**Comment by johalun** [comment]
That works! Although I see in the hegel logs that multiple other requests are done and denied.

```
hegel_1                     | {"level":"info","ts":1643834414.9097157,"caller":"http-server/http_handlers.go:109","msg":"got ip from request","service":"github.com/tinkerbell/hegel","pkg":"main","userIP":"10.214.134.1"}
hegel_1                     | {"level":"info","ts":1643834414.9113317,"caller":"http-server/http_handlers.go:113","msg":"failed to get hardware by ip","service":"github.com/tinkerbell/hegel","pkg":"main","userIP":"10.214.134.1","error":"rpc error: code = Unknown desc = SELECT: sql: no rows in result set"}
hegel_1                     | {"level":"info","ts":1643835115.861287,"caller":"http-server/http_handlers.go:109","msg":"got ip from request","service":"github.com/tinkerbell/hegel","pkg":"main","userIP":"10.214.134.1"}
hegel_1                     | {"level":"info","ts":1643835115.863123,"caller":"http-server/http_handlers.go:113","msg":"failed to get hardware by ip","service":"github.com/tinkerbell/hegel","pkg":"main","userIP":"10.214.134.1","error":"rpc error: code = Unknown desc = SELECT: sql: no rows in result set"}
hegel_1                     | {"level":"info","ts":1643843512.9028368,"caller":"http-server/http_handlers.go:109","msg":"got ip from request","service":"github.com/tinkerbell/hegel","pkg":"main","userIP":"10.214.134.1"}
hegel_1                     | {"level":"info","ts":1643843512.9047494,"caller":"http-server/http_handlers.go:113","msg":"failed to get hardware by ip","service":"github.com/tinkerbell/hegel","pkg":"main","userIP":"10.214.134.1","error":"rpc error: code = Unknown desc = SELECT: sql: no rows in result set"}
hegel_1                     | {"level":"info","ts":1643843548.9161088,"caller":"http-server/http_handlers.go:109","msg":"got ip from request","service":"github.com/tinkerbell/hegel","pkg":"main","userIP":"10.214.134.12"}
```

The last one is my successful one using XFF header and trusted proxy set. I don't know what the others are, but provisioning is working so I guess it's not critical.

**Comment by mmlb** [comment]
ok great! Nothing comes to mind for me for those other calls...
