### ISSUE TITLE
0.7.0 Tracking

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/hegel#89]
A ticket for tracking 0.7.0.

**Comment by chrisdoherty4** [comment]
#84, #86 and #87 introduce a new, standardized set of CLI options with significant rework of internals (behavior unaffected). #84 also specifies some deprecation in the help menu of the non-standardized versions of configuration. 0.7.0 can be the deprecation release and 0.8.0 could be the removal given we don't have any backward compatibility promise for this service yet (major version 0 n'all).

Additionally, #82 introduces a Kubernetes back-end that would be good to have in 0.7.0.

What else would be useful to throw in?

**Comment by displague** [comment]
Milestone created: https://github.com/tinkerbell/hegel/milestone/1
The issues you identified have been added.

**Comment by chrisdoherty4** [comment]
Closed in favor of milestones. Can re-open if we need a dedicated issue.
