### ISSUE TITLE
0.8.0 Tracking

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/hegel#91]
Tracking issue for 0.8.0

[Previous release tracking issue](https://github.com/tinkerbell/hegel/issues/89).

**Comment by chrisdoherty4** [comment]
Remove all CLI and env configuration deprecated in [0.7.0](#89)

**Comment by displague** [comment]
Milestone created: https://github.com/tinkerbell/hegel/milestone/2
The issues you identified have been added.

**Comment by chrisdoherty4** [comment]
Closed in favor of populating milestones.
